### PR TITLE
Update Paralayout framework, tests and corresponding studio app to Swift 4.2

### PR DESCRIPTION
**Pull request by SoaurabhK**
- [x] Update Paralayout framework, tests and corresponding studio app targets to Swift 4.2
- [x] Enable warning for `DEPRECATED_OBJC_IMPLEMENTATIONS` and `OBJC_IMPLICIT_RETAIN_SELF`
- [x] Remove `inset(by:)` from `GeometryAdditions` as it's available by default with Swift 4.2
- [x] Update swift-version, travis.yml, podspec and README files
- [x] Update Gemfile to use latest stable version CocoaPods version 1.5.3 

Note - CocoaPods 1.5.3 fixes - https://github.com/CocoaPods/CocoaPods/issues/7765, the earlier version(1.5.0) was causing a build error.

Resolves Issue - https://github.com/square/Paralayout/issues/12

### CODE REVIEW

**Comment by SoaurabhK** [comment]
Travis is running CI on Xcode8.2, which does not support Swift 4.2

**Comment by SoaurabhK** [comment]
@pwesten Just curious, are we maintaining this project ?

**Comment by pwesten** [comment]
@SoaurabhK Yes we are (and expect some refinement pretty soon), thanks for giving this a bump!

**Comment by dfed** [comment]
My guess is the build is failing because [.travis.yml](https://github.com/square/Paralayout/blob/0.8/.travis.yml) is using Xcode 8.2, which doesn't support Swift 4.2.

If we want this PR to land without requiring a major version bump, you'll need to:
1. Use `#if swift` syntax to conditionally change the code for Swift 4.2 vs Swift 3 (note that the current minimum supported version this library supports is Swift 3).
1. Not remove the `inset(by` method. Though it'd be reasonable to deprecate that method.

If you're okay with a major version bump, to get this compiling you'll need to update the `.travis.yml` to use Xcode 10. Note that it'd be good practice to update the `README` to reflect the new minimum version as well. You'll likely also want to update the `.swift-version` file to point at `4.0` instead of `3.0`.

**Comment by pwesten** [comment]
Thanks for the roadmap @dfed ! I'm perfectly fine bumping the version and requirements (Xcode 8 is awfully old).

**Comment by SoaurabhK** [comment]
@pwesten @dfed I have updated the PR as discussed. Mainly it updates versions in swift-version, travis.yml, podspec, README, and Gemfile. 

One important thing is CocoaPods next stable version will be 1.6.0, which would require an explicit bump, open to discuss more around this.

**Comment by SoaurabhK** [comment]
@pwesten Happy to contribute, I believe we can now mark https://github.com/square/Paralayout/issues/12 as resolved/closed.

**Comment by dfed** [comment]
Once 0.9 is released, yes 🙂

**Pull request merged**
